import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { ReactQueryClientProvider } from "./QueryClientProvider";
import { cn } from "@/lib/utils";
import { Navbar } from "./Navbar";
import { UserProvider } from "./hooks/useUser";

const pretendard = localFont({
  src: [
    {
      path: "../public/fonts/Pretendard-Light.woff2",
      weight: "300",
    },
    {
      path: "../public/fonts/Pretendard-Regular.woff2",
      weight: "400",
    },
    {
      path: "../public/fonts/Pretendard-Bold.woff2",
      weight: "700",
    },
  ],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <UserProvider>
        <html lang="en" suppressHydrationWarning>
          <body className={cn(pretendard.className, "min-h-screen grid grid-rows-[auto_1fr_auto]")}>
            <Navbar />
            <main className="col-span-1 px-4 pt-10 md:px-20 w-full bg-slate-100">{children}</main>
            <Toaster />
          </body>
        </html>
      </UserProvider>
    </ReactQueryClientProvider>
  );
}
