import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import QueryClientProvider from "./QueryClientProvider";
import { cn } from "@/lib/utils";
import { Navbar } from "./Navbar";

const pretendard = localFont({
  src: [
    {
      path: "../public/fonts/Pretendard-Light.woff2",
      weight: "300",
    },
    {
      path: "../public/fonts/Pretendard-Regular.woff2",
      weight: "400",
    },
    {
      path: "../public/fonts/Pretendard-Bold.woff2",
      weight: "700",
    },
  ],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="h-full">
      <body className={cn(pretendard.className, "h-full")}>
        <QueryClientProvider>
          <Navbar />
          <main className="p-5 max-w-2xl m-auto">{children}</main>
          <Toaster />
        </QueryClientProvider>
      </body>
    </html>
  );
}
